Repository MyOnlineStore/common-domain, pull requests merged in 2020-09, with the labels that each got.

#33 Expanded pattern for parsing an address line into separate address components
  psalm-baseline.xml
  src/Value/Location/Address/Street.php
  tests/Value/Location/Address/StreetTest.php
Labels: bug

#34 MWW-8224 - Loosen street parsing patterns
  src/Value/Location/Address/Street.php
  src/Value/Money/Money.php
  tests/Value/Location/Address/StreetTest.php
  tests/Value/Money/MoneyTest.php
Labels: bug

#35 Make all naming equality checks case insensitive
  src/Value/Location/Address/City.php
  src/Value/Location/Address/StreetName.php
  src/Value/Location/Address/StreetNumber.php
  src/Value/Location/Address/StreetSuffix.php
  src/Value/Person/Name/FirstName.php
  src/Value/Person/Name/LastName.php
  tests/Value/Location/Address/CityTest.php
  tests/Value/Location/Address/StreetNameTest.php
  tests/Value/Location/Address/StreetNumberTest.php
  tests/Value/Location/Address/StreetSuffixTest.php
  tests/Value/Person/Name/FirstNameTest.php
  tests/Value/Person/Name/LastNameTest.php
Labels: enhancement

#37 CASH-1607 - Add BIC VO
  src/Exception/Finance/InvalidBic.php
  src/Value/Finance/Bic.php
  tests/Exception/Finance/InvalidBicTest.php
  tests/Value/Finance/BicTest.php
Labels: sprint

#38 Always cast an email address to lowercase
  src/Value/Mail/EmailAddress.php
  tests/Value/Mail/EmailAddressTest.php
Labels: bug

#36 CASH-1597 - Add phone number country code accessor
  src/Value/Contact/PhoneNumber.php
  tests/Value/Contact/PhoneNumberTest.php
Labels: sprint
